[theme]
primaryColor = "#1DB954"              # Spotify green
backgroundColor = "#121212"           # dark background
secondaryBackgroundColor = "#181818"  # card / sidebar background
textColor = "#FFFFFF"
font = "sans serif"
